### ISSUE TITLE
TaskVineExecutor fails sometimes in CI with failure to create a factory working directory

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#3089]
**Describe the bug**

In CI, some noticeable fraction of the time (10-20% informally), I've started noticing these errors in the taskvine CI test, followed by a hang of that test run (I'm assuming the hang happens because this code does not converge to failure when this exception happens)

I've been busy investigating another regular hang in CI recently, and so I hadn't noticed that this had started happening...

Attached is a runinfo tarball showing this happening. 
[runinfo-3.9-3081-merge-5fb7f9d49e5007c26d96dc112aacbfc9eb387158.zip](https://github.com/Parsl/parsl/files/14337404/runinfo-3.9-3081-merge-5fb7f9d49e5007c26d96dc112aacbfc9eb387158.zip)

look in .pytest/parsltest-20240219.204702-parsl_tests_configs_taskvine_ex_py-qv7z7h4r/runinfo/000/parsl.log in that tarball, for example, for another example of this exception.

```
1708379692.027022 2024-02-19 21:54:52 TaskVine-Factory-Process-8251 MainThread-140306450089792 parsl.process_loggers:31 wrapped ERROR: Exceptional ending for _taskvine_factory on thread MainThread
Traceback (most recent call last):
  File "/home/runner/work/parsl/parsl/parsl/process_loggers.py", line 27, in wrapped
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/parsl/parsl/parsl/executors/taskvine/factory.py", line 66, in _taskvine_factory
    with factory:
  File "/tmp/cctools/lib/python3.8/site-packages/ndcctools/taskvine/manager.py", line 1905, in __enter__
    return self.start()
           ^^^^^^^^^^^^
  File "/tmp/cctools/lib/python3.8/site-packages/ndcctools/taskvine/manager.py", line 1867, in start
    self.scratch_dir = tempfile.mkdtemp(prefix="vine-factory-", dir=self.scratch_dir)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/tempfile.py", line 384, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/parsl/parsl/.pytest/parsltest-current/runinfo/TaskVineExecutor/vine-factory-zcefx55o'
```

I wonder if there's a race condition with whatever creates the parent `TaskVineExecutor` directory. Note that this is different from the TaskVineExecutor directory that appears as runinfo/*000*/TaskVineExecutor.

cc @dthain @tphung3 

**To Reproduce**
run CI a few times

**Comment by benclifford** [comment]
from very rough reading of taskvine source - that code in the stacktrace is assuming that self.scratch_dir (as passed to the factory) exists - but that directory is not created until the manager starts up which happens (I think) asynchronously to the factory code starting up (all of these launched fairly concurrently in parsl/executors/taskvine/executor.py `def start` method)

**Comment by dthain** [comment]
Thank you @benclifford, linking to TaskVine issue https://github.com/cooperative-computing-lab/cctools/issues/3667

**Comment by dthain** [comment]
Fixed in source, release pending shortly...
https://github.com/cooperative-computing-lab/cctools/pull/3672

**Comment by benclifford** [comment]
https://github.com/cooperative-computing-lab/cctools/pull/3672 tries to fix this, but I still encounter it (after some other fiddling around in the `desc` branch of Parsl) -- the 2nd path in cctools 3672 only creates the directory if it is not specified. i have looked at what is happening with the first part of 3672 and whether it is relevant to my situation. my quick fix in `desc` is to os.makedirs at the point that the code sets the factory scratch dir (for a hopefully straightforward: if the directory is specified, it must also definitely exist).

as I work through `desc` branch stuff, this will probably get pushed to master eventually.

**Comment by dthain** [comment]
@colinthomas-z80 please take a look and see what else needs to be done on the cctools side.

**Comment by benclifford** [comment]
@colinthomas-z80 this change to `factory.py` is I think roughly the fix: if scratch_dir is specified, it must exist, and this change makes it so:

```
diff --git a/parsl/executors/taskvine/factory.py b/parsl/executors/taskvine/factory.py
index 20409efac8..11cbeeb623 100644
--- a/parsl/executors/taskvine/factory.py
+++ b/parsl/executors/taskvine/factory.py
@@ -1,4 +1,5 @@
 import logging
+import os
 
 from parsl.executors.taskvine.errors import TaskVineFactoryFailure
 from parsl.process_loggers import wrap_with_logs
@@ -43,6 +44,10 @@ def _taskvine_factory(should_stop, factory_config):
     factory.max_workers = factory_config.max_workers
     factory.workers_per_cycle = factory_config.workers_per_cycle
 
+    # fix race condition where this directory isn't created by the
+    # factory - despite parsl issue #3089, cctools #3672
+    os.makedirs(factory.scratch_dir, exist_ok=True)
+
     if factory_config.worker_options:
         factory.extra_options = factory_config.worker_options
     factory.timeout = factory_config.worker_timeout
```
